### ISSUE TITLE
Be ready for Python 3 by switching to print_function

### ISSUE THREAD

**Issue by cclauss** [iApeiron/Savethemblobs_app#2]
Uncomment https://github.com/iApeiron/Savethemblobs_app/blob/master/Script/savethemblobs.py#L16

**Comment by iApeiron** [comment]
I'll have a look at applying this. Thank you.
savethembobs.py is imported from [the main repo here,](https://github.com/iApeiron/savethemblobs) so I will have to commit your changes there too.
Do you have any further improvements for the control script "main.py"? I have not yet implemented your last suggestion from the forum.

**Comment by iApeiron** [comment]
Fixed
